### ISSUE TITLE
Computer resolution not large enough

### ISSUE THREAD

**Issue by GreekGeek64** [etherealxx/limbo-godot#2]
I tried using this fun game, but I encountered a problem. The last 2 keys, the ones that appear at the bottom, don't show up fully during the entire session. That means that, if one of the bottom keys were to be the right one befoe the shuffling, I won't be able to see it and would have to guess which one I need to follow. To make matters worse, after all the shuffling finishes, the key selection works perfectly normal, but the cutscene of getting the wrong key also goes off-camera.
![image](https://github.com/etherealxx/limbo-godot/assets/167864376/8c695d8a-7eea-4587-87f0-fdad6da67183)

**Comment by etherealxx** [comment]
Hello, thanks for downloading my game, really appreciated😊
So yeah, i made this game with only my pc as a testing device, and i'm aware device with lower resolution won't display the key correctly.
Since the key window are 150x150 in size, and the gap between the key rows are 50 pixels, so it needs screen resolution atleast higher than 900px in height.
Could you provide your screen resolution? like the height and the width. I might try to fix that for you

**Comment by TheAwesomeZave** [comment]
it's 1366x768, considering my monitor cuts the last keys at the exact same point
(also yeah the bsod is cut off too)

**Comment by etherealxx** [comment]
@TheAwesomeZave thanks, turns out i have a laptop that i can use for testing with roughly the same resolution.
I'm also aware about the BSOD problem, and two more things, which is the app doesn't work on certain old AMD devices, and sound desync on lower end hardware. (basically the shuffle going on slower rate and still going even though the song is already over). I'll try to fix those.

**Comment by etherealxx** [comment]
Hello everyone. I released a new patch, it should fix the small resolution issue, and some other bugs.
https://github.com/etherealxx/limbo-godot/releases/tag/v1.2.0
Feel free to open this issue if the same bugs still happens on your side.✨
